stages:
  - build-deploy

services:
  - docker:dind

before_script:
  - apt-get update
  # - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" "$CI_REGISTRY"

build-deploy:
  stage: build-deploy
  when: manual
  script:
    - echo "${ENV}" > .env
    - docker compose up
    # - docker build -t $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA .
    # - docker push $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA
    # - docker stop my_laravel_app || true
    # - docker rm my_laravel_app || true
    # - docker run -d --name my_laravel_app -p 1112:80 $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA
  tags:
    - devfh
  after_script:
    - echo "Deploy Done"
  allow_failure: false
