stages:
  - build-deploy

services:
  - docker:dind

before_script:
  - wget https://gitlab.com/fahrialmd/memoburst/-/raw/main/docker-compose.yml?ref_type=heads -O docker-compose.yml
  - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" "$CI_REGISTRY"

build-deploy:
  stage: build-deploy
  when: manual
  script:
    - echo "${ENV}" > .env
    - docker compose down
    - docker compose up -d --build
    - docker cp .env nextapp:/app
    - docker compose restart
  tags:
    - devfh
  after_script:
    - echo "Deploy Done"
  allow_failure: false
